services:
  - type: web
    name: provenadigitalassets-backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn zcore.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
      - key: DJANGO_SETTINGS_MODULE
        value: zcore.settings