# Generated by Django 4.2.7 on 2025-10-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., USDT, Bitcoin, Ethereum', max_length=50, unique=True)),
                ('type', models.CharField(choices=[('deposit', 'Deposit Only'), ('withdrawal', 'Withdrawal Only'), ('both', 'Both')], default='both', max_length=20)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='payment_methods/')),
                ('min_amount', models.DecimalField(decimal_places=2, default=10.0, max_digits=15)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for no limit', max_digits=15, null=True)),
                ('charge_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage')], default='percentage', max_length=20)),
                ('charge_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount or percentage based on charge type', max_digits=10)),
                ('duration', models.CharField(blank=True, help_text="e.g., '1-24 hours', 'Instant'", max_length=100)),
                ('wallet_address', models.CharField(blank=True, help_text='Platform wallet address for receiving payments', max_length=200)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='payment_qr_codes/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['order', 'name'],
            },
        ),
    ]
