# Generated by Django 4.2.7 on 2026-03-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
